name: tvbox
description: Live channels for TVBox.
version: 1.0.0
homepage: https://github.com/moky/TVBox
repository: https://github.com/moky/TVBox
issue_tracker: https://github.com/moky/TVBox/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
